name: Scala

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    name: Test Scala
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        java-version:
          - 8
          - 11
          - 17
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: corretto
          cache: sbt

      - name: sbt test
        working-directory: ./scala
        run: sbt test

  # https://github.com/orgs/community/discussions/12395
  all-success:
    name: All success (Scala)
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      - if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
        run: exit 1

